/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWeekRouteImport } from './routes/api/week'
import { Route as ApiStrategyRouteImport } from './routes/api/strategy'
import { Route as ApiPaymentWebhookRouteImport } from './routes/api/payment-webhook'
import { Route as ApiPaymentRouteImport } from './routes/api/payment'

const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeekRoute = ApiWeekRouteImport.update({
  id: '/api/week',
  path: '/api/week',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrategyRoute = ApiStrategyRouteImport.update({
  id: '/api/strategy',
  path: '/api/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookRoute = ApiPaymentWebhookRouteImport.update({
  id: '/api/payment-webhook',
  path: '/api/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentRoute = ApiPaymentRouteImport.update({
  id: '/api/payment',
  path: '/api/payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/strategies': typeof StrategiesRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/payment-webhook': typeof ApiPaymentWebhookRoute
  '/api/strategy': typeof ApiStrategyRoute
  '/api/week': typeof ApiWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/strategies': typeof StrategiesRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/payment-webhook': typeof ApiPaymentWebhookRoute
  '/api/strategy': typeof ApiStrategyRoute
  '/api/week': typeof ApiWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/strategies': typeof StrategiesRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/payment-webhook': typeof ApiPaymentWebhookRoute
  '/api/strategy': typeof ApiStrategyRoute
  '/api/week': typeof ApiWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/pricing'
    | '/strategies'
    | '/api/payment'
    | '/api/payment-webhook'
    | '/api/strategy'
    | '/api/week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/pricing'
    | '/strategies'
    | '/api/payment'
    | '/api/payment-webhook'
    | '/api/strategy'
    | '/api/week'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/pricing'
    | '/strategies'
    | '/api/payment'
    | '/api/payment-webhook'
    | '/api/strategy'
    | '/api/week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  StrategiesRoute: typeof StrategiesRoute
  ApiPaymentRoute: typeof ApiPaymentRoute
  ApiPaymentWebhookRoute: typeof ApiPaymentWebhookRoute
  ApiStrategyRoute: typeof ApiStrategyRoute
  ApiWeekRoute: typeof ApiWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/week': {
      id: '/api/week'
      path: '/api/week'
      fullPath: '/api/week'
      preLoaderRoute: typeof ApiWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strategy': {
      id: '/api/strategy'
      path: '/api/strategy'
      fullPath: '/api/strategy'
      preLoaderRoute: typeof ApiStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-webhook': {
      id: '/api/payment-webhook'
      path: '/api/payment-webhook'
      fullPath: '/api/payment-webhook'
      preLoaderRoute: typeof ApiPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment': {
      id: '/api/payment'
      path: '/api/payment'
      fullPath: '/api/payment'
      preLoaderRoute: typeof ApiPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  StrategiesRoute: StrategiesRoute,
  ApiPaymentRoute: ApiPaymentRoute,
  ApiPaymentWebhookRoute: ApiPaymentWebhookRoute,
  ApiStrategyRoute: ApiStrategyRoute,
  ApiWeekRoute: ApiWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
